apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: aviaigz/streamlit:0.6.0
        imagePullPolicy: Always
        env:
        - name: "V3IO_ACCESS_KEY"
          value: "F/LSkDHIZg3/3Qu4qIjqU41jGgi2Fh2VCyveBiKl"
        - name: "FRAMES_URI"
          value: <FRAMES_URI>
        - name: "KV_TABLE_PATH"
          value: "<USER_NAME>/examples/faces/artifacts/encodings"
        - name: "CONTAINER"
          value: "users"
        ports:
        - containerPort: 8501
        command: ["streamlit", "run", "/User/demos/realtime-face-recognition/streamlit/dashboard.py" ]
        args: []
        volumeMounts:
        - mountPath: User
          name: fs
      volumes:
      - flexVolume:
          driver: v3io/fuse
          options:
            accessKey: "F/LSkDHIZg3/3Qu4qIjqU41jGgi2Fh2VCyveBiKl"
            container: users
            subPath: /<USER_NAME>
        name: fs
---
kind: Service
apiVersion: v1
metadata:
  name: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    nodePort: 30090
    port: 8501
    targetPort: 8501
